services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.10"
      DIFFICULTY: "hard"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      ONLINE_MODE: "TRUE"
      ENABLE_COMMAND_BLOCK: "true"
      PAPER_WORLD_DEFAULTS__UNSUPPORTED_SETTINGS__ALLOW_PISTON_DUPLICATION: "true"
      PAPER_WORLD_DEFAULTS__UNSUPPORTED_SETTINGS__ALLOW_PERMANENT_BLOCK_BREAK_EXPLOITS: "true"
      PAPER_WORLD_DEFAULTS__UNSUPPORTED_SETTINGS__ALLOW_UNSAFE_END_PORTAL_TELEPORTATION: "true"
    ports:
      - "25565:25565"
    volumes:
      - /srv/minecraft/paper-hard:/data
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
